#pragma once
// Generated by build script, do not edit!
#define UNITY_VERSION "2019.2.17f1"
#define UNITY_VERSION_DIGITS "2019.2.17"
#define UNITY_VERSION_SUFFIX "f1"
#define UNITY_VERSION_VER 2019
#define UNITY_VERSION_MAJ 2
#define UNITY_VERSION_MIN 17
#define UNITY_IS_BETA 0
